"""empty message

Revision ID: 72dcef4700bf
Revises: 5c71f9d4cfb0
Create Date: 2019-05-19 13:59:07.666475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72dcef4700bf'
down_revision = '5c71f9d4cfb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slave', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slave', 'created_at')
    # ### end Alembic commands ###
